[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build.environment]
  NODE_VERSION = "18"

[[scheduled]]
  name = "sendPeriodicReminders"
  cron = "0 0 * * *" # Runs every day at midnight