[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[scheduled]]
  name = "sendPeriodicReminders"
  cron = "0 0 * * *" # Runs every day at midnight