// Generated by manage-types script
export interface Category {
  id: string;
  title: string;
  type: string;
  color?: string;
  icon?: string;
  is_default?: boolean;
  user_id: string;
  created_at?: string;
}

export interface CategoryBreakdownChartProps {
  selectedMonth: string;
}